### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lnakhul** [mageprince/magento2-FAQ#1]
When clicking on managed Faq group or manage faq it redirecting to Dashboard. Is this because I'm using Magento 2.1.9?

**Comment by mageprince** [comment]
Hi @Inakhul,
This extension working well in all 2.1.x. Also checked in default Magento 2.1.9. See Screenshot.
![faqgroup magento admin](https://user-images.githubusercontent.com/24751863/31027712-dc234b68-a568-11e7-9fa8-12a21e5c5d22.png)
