### ISSUE TITLE
Accordion not working, please help 

### ISSUE THREAD

**Issue by TeodorBogdanov** [mageprince/magento2-FAQ#10]
Hi there, I've installed the FAQ plugin in a test environment(maintenance mode) and changed the colours in the  CSS file to fit the overall design of the website. Unfortunately when I go to my FAQ page the colours have been changed, but if I decide to go to another page(home page p.e.) and then go back to the FAQ page - the accordion has disappeared and all the questions/answers are open? Any help will be appreciated! 
![screen shot 2018-08-07 at 12 59 40](https://user-images.githubusercontent.com/42173762/43772266-ceedc71a-9a41-11e8-8260-de299172559a.png)

**Comment by mageprince** [comment]
Hi @TeodorBogdanov, thank you for your report. I was not able to reproduce this issue in clean/default installation. Please provide site link to check the issue.

**Comment by TeodorBogdanov** [comment]
the site is in maintenance mode so I'd have to give you login details for the backend and once logged in there you will be able to see it . I will email you separately with the login details, shop.gem-a.com @mageprince

**Comment by TeodorBogdanov** [comment]
@mageprince I have sent an email with the password to this email - 7pprince@gmail.com - can you confirm if you've received it please?

**Comment by mageprince** [comment]
Hi @TeodorBogdanov,

I didn't got any mail. I need not admin details. just give me store front
url to check the exact issue.

**Comment by TeodorBogdanov** [comment]
shop.gem-a.com @mageprince

**Comment by mageprince** [comment]
@TeodorBogdanov I already tried but it's in maintenance mode.

**Comment by TeodorBogdanov** [comment]
That's why I said I have to send you login details and if you logged in to the admin panel and try to go to shop.gem-a.com/faq you will able to see the store front! can you send you email address please ? @mageprince

**Comment by mageprince** [comment]
Please send details in mail.mageprince@gmail.com I will check the issue at
tomorrow

**Comment by mageprince** [comment]
@TeodorBogdanov I had checked your site and not found any issue. I already checked with the different browser with the full refresh but it's working fine.
