### ISSUE TITLE
2 exception(s):

### ISSUE THREAD

**Issue by tarigms** [mageprince/magento2-FAQ#13]
2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'offersg_shiny.prince_faqgroup' doesn't exist, query was: SELECT `main_table`.* FROM `prince_faqgroup` AS `main_table`
Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'offersg_shiny.prince_faqgroup' doesn't exist

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'offersg_shiny.prince_faqgroup' doesn't exist, query was: SELECT `main_table`.* FROM `prince_faqgroup` AS `main_table`
#0 /home/offersg/public_html/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/offersg/public_html/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /home/offersg/public_html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/offersg/public_html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /home/offersg/public_html/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(533): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /home/offersg/public_html/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(605): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#6 /home/offersg/public_html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array)
#8 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection/AbstractDb.php(774): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#9 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection/AbstractDb.php(670): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#10 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection/AbstractDb.php(574): Magento\Framework\Data\Collection\AbstractDb->getData()
#11 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection/AbstractDb.php(559): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#12 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection.php(831): Magento\Framework\Data\Collection\AbstractDb->load()
#13 /home/offersg/public_html/magento2/app/code/Prince/Faq/Ui/Component/Listing/Column/FaqGroup.php(26): Magento\Framework\Data\Collection->getIterator()
#14 /home/offersg/public_html/magento2/vendor/magento/module-ui/Component/Form/Element/AbstractOptionsField.php(55): Prince\Faq\Ui\Component\Listing\Column\FaqGroup->toOptionArray()
#15 /home/offersg/public_html/magento2/vendor/magento/module-ui/Component/Listing/Columns/Column.php(79): Magento\Ui\Component\Form\Element\AbstractOptionsField->prepare()
#16 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(159): Magento\Ui\Component\Listing\Columns\Column->prepare()
#17 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(156): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Listing\Columns\Column))
#18 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(156): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Listing\Columns))
#19 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(137): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Listing))
#20 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(97): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'prince_faq_inde...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#21 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#22 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout.php(343): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#23 /home/offersg/public_html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#24 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#25 /home/offersg/public_html/magento2/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#26 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#27 /home/offersg/public_html/magento2/vendor/magento/framework/View/Page/Config.php(208): Magento\Framework\View\Layout\Builder->build()
#28 /home/offersg/public_html/magento2/vendor/magento/framework/View/Page/Config.php(228): Magento\Framework\View\Page\Config->build()
#29 /home/offersg/public_html/magento2/generated/code/Magento/Framework/View/Page/Config/Interceptor.php(50): Magento\Framework\View\Page\Config->getTitle()
#30 /home/offersg/public_html/magento2/app/code/Prince/Faq/Controller/Adminhtml/Faq/Index.php(33): Magento\Framework\View\Page\Config\Interceptor->getTitle()
#31 /home/offersg/public_html/magento2/generated/code/Prince/Faq/Controller/Adminhtml/Faq/Index/Interceptor.php(24): Prince\Faq\Controller\Adminhtml\Faq\Index->execute()
#32 /home/offersg/public_html/magento2/vendor/magento/framework/App/Action/Action.php(107): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->execute()
#33 /home/offersg/public_html/magento2/vendor/magento/module-backend/App/AbstractAction.php(235): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->___callParent('dispatch', Array)
#36 /home/offersg/public_html/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /home/offersg/public_html/magento2/generated/code/Prince/Faq/Controller/Adminhtml/Faq/Index/Interceptor.php(39): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->___callPlugins('dispatch', Array, NULL)
#40 /home/offersg/public_html/magento2/vendor/magento/framework/App/FrontController.php(55): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#41 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#43 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#44 /home/offersg/public_html/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#45 /home/offersg/public_html/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#46 /home/offersg/public_html/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#47 /home/offersg/public_html/magento2/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()
#48 /home/offersg/public_html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#49 {main}

Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'offersg_shiny.prince_faqgroup' doesn't exist
#0 /home/offersg/public_html/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /home/offersg/public_html/magento2/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#2 /home/offersg/public_html/magento2/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /home/offersg/public_html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /home/offersg/public_html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#5 /home/offersg/public_html/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(533): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#6 /home/offersg/public_html/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(605): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#7 /home/offersg/public_html/magento2/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#8 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection/Db/FetchStrategy/Query.php(21): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array)
#9 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection/AbstractDb.php(774): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#10 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection/AbstractDb.php(670): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#11 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection/AbstractDb.php(574): Magento\Framework\Data\Collection\AbstractDb->getData()
#12 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection/AbstractDb.php(559): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#13 /home/offersg/public_html/magento2/vendor/magento/framework/Data/Collection.php(831): Magento\Framework\Data\Collection\AbstractDb->load()
#14 /home/offersg/public_html/magento2/app/code/Prince/Faq/Ui/Component/Listing/Column/FaqGroup.php(26): Magento\Framework\Data\Collection->getIterator()
#15 /home/offersg/public_html/magento2/vendor/magento/module-ui/Component/Form/Element/AbstractOptionsField.php(55): Prince\Faq\Ui\Component\Listing\Column\FaqGroup->toOptionArray()
#16 /home/offersg/public_html/magento2/vendor/magento/module-ui/Component/Listing/Columns/Column.php(79): Magento\Ui\Component\Form\Element\AbstractOptionsField->prepare()
#17 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(159): Magento\Ui\Component\Listing\Columns\Column->prepare()
#18 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(156): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Listing\Columns\Column))
#19 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(156): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Listing\Columns))
#20 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(137): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Listing))
#21 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Generator/UiComponent.php(97): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'prince_faq_inde...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#22 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#23 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout.php(343): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#24 /home/offersg/public_html/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#25 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#26 /home/offersg/public_html/magento2/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#27 /home/offersg/public_html/magento2/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#28 /home/offersg/public_html/magento2/vendor/magento/framework/View/Page/Config.php(208): Magento\Framework\View\Layout\Builder->build()
#29 /home/offersg/public_html/magento2/vendor/magento/framework/View/Page/Config.php(228): Magento\Framework\View\Page\Config->build()
#30 /home/offersg/public_html/magento2/generated/code/Magento/Framework/View/Page/Config/Interceptor.php(50): Magento\Framework\View\Page\Config->getTitle()
#31 /home/offersg/public_html/magento2/app/code/Prince/Faq/Controller/Adminhtml/Faq/Index.php(33): Magento\Framework\View\Page\Config\Interceptor->getTitle()
#32 /home/offersg/public_html/magento2/generated/code/Prince/Faq/Controller/Adminhtml/Faq/Index/Interceptor.php(24): Prince\Faq\Controller\Adminhtml\Faq\Index->execute()
#33 /home/offersg/public_html/magento2/vendor/magento/framework/App/Action/Action.php(107): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->execute()
#34 /home/offersg/public_html/magento2/vendor/magento/module-backend/App/AbstractAction.php(235): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->___callParent('dispatch', Array)
#37 /home/offersg/public_html/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#38 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /home/offersg/public_html/magento2/generated/code/Prince/Faq/Controller/Adminhtml/Faq/Index/Interceptor.php(39): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->___callPlugins('dispatch', Array, NULL)
#41 /home/offersg/public_html/magento2/vendor/magento/framework/App/FrontController.php(55): Prince\Faq\Controller\Adminhtml\Faq\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#43 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#44 /home/offersg/public_html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#45 /home/offersg/public_html/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#46 /home/offersg/public_html/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#47 /home/offersg/public_html/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#48 /home/offersg/public_html/magento2/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()
#49 /home/offersg/public_html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#50 {main}

**Comment by mageprince** [comment]
Hi @tarigms 
Please remove an entry of `Prince_Faq` from `setup_module` table from the database. Then run following commands again.

php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
