### ISSUE TITLE
Accordion is not working.

### ISSUE THREAD

**Issue by mencomcorp** [mageprince/magento2-FAQ#14]
If I open the page in the private mode, the accordion is working. But if I refresh the page the accordion, the function is gone. The website is in my developer's local server and all the caches are disabled at the moment.

Here is the problem page and I'm using the Fatest theme of Codazon.

https://mencom.vn.cisinlive.com/faq

**Before refresh**
![before refresh](https://user-images.githubusercontent.com/47043247/51774064-f5ba1980-20be-11e9-8e31-f9e3ff6eb4af.JPG)

**After refresh**
![after refresh](https://user-images.githubusercontent.com/47043247/51774063-f5ba1980-20be-11e9-873e-398399d17af8.JPG)

Please advise.

Thank you,
Eddie

**Comment by mageprince** [comment]
Hi @mencomcorp 
I just checked your link: https://mencom.vn.cisinlive.com/faq with private windows and its working fine without any issue with a hard refresh.

**Comment by mencomcorp** [comment]
Hi,

Can you please go to the page in the new window (not the private window) and refresh the page?

The accordion doesn’t work. Even though you are in the private window, if you just refresh the page (not hard refresh), you can see the issue.

Please advise.

Thank you,

[Email-logo]<https://www.mencom.com/>

Eddie Choi / Marketing Coordinator eddie.choi@mencom.com<mailto:eddie.choi@mencom.com>
1-770-534-4585
www.mencom.com<http://www.mencom.com/>

**Comment by mencomcorp** [comment]
Can you please go to the page in the new window (not the private window) and refresh the page?

The accordion doesn’t work. Even though you are in the private window, if you just refresh the page (not hard refresh), you can see the issue.

Please advise.

**Comment by Sagar2-cyber** [comment]
I am facing the same issue. Please share the solution.
