### ISSUE TITLE
Accordian jquery not loading in frontend crome browser only

### ISSUE THREAD

**Issue by koushikch7** [mageprince/magento2-FAQ#15]
we have checked several times and updated code form git too, but when I am working on development everything works fine but when I set the mode to production then except chrome browser all other browsers are able to produce expected results in the frontend but not the same with the crome.

you may check with the link http://staging.cotstyle.com/faq.

please let me know the earliest.

**Comment by mageprince** [comment]
@koushikch7 You have other js errors with following third party js. Please remove it and check again.

`
 gtag('event', 'conversion', {
  | 'send_to': 'AW-878955940/xsVTCIGu8Y8BEKSbj6MD',
  | 'value': 1.0,
  | 'currency': 'INR',
  | 'transaction_id': '<%= orderId %>'
  | });
`
