### ISSUE TITLE
Unable to upload Image for FAQ Group

### ISSUE THREAD

**Issue by pjassal** [mageprince/magento2-FAQ#17]
Hi

I have magento 2.3.0 installed. I have installed the Porto theme and recently installed the MagePrince FAQ extension. I have setup up groups and added questions. I am trying to change the default icon for the groups but I am unable to upload a new image.

When I click on upload I am able to select an image and click upload. After which nothing happens. You can see the small progress wheel spinning but nothing happens. 

I have tried on Safari and Chrome. Am I correct in thinking that this module will not work fully on 2.3.0? Is there a work around?

Thank you

This screen shot shows the progress wheel next to the Upload button.
<img width="1440" alt="Screenshot 2019-03-29 at 12 54 47" src="https://user-images.githubusercontent.com/46371628/55231070-dc9a2a00-5221-11e9-9c8d-a5ae224b2163.png">
 
The below error message can be seen in the Javascript Console and the line in code that is throwing an error. 

<img width="1440" alt="Screenshot 2019-03-29 at 12 55 53" src="https://user-images.githubusercontent.com/46371628/55231180-22ef8900-5222-11e9-8be3-d0e051c69ac8.png">
<img width="1440" alt="Screenshot 2019-03-29 at 12 55 48" src="https://user-images.githubusercontent.com/46371628/55231181-23881f80-5222-11e9-895d-129116089d3b.png">

**Comment by mageprince** [comment]
Hi, @pjassal This module is tested with Magento 2.3.x. Recently tested with Magento 2.3.2. Please disable all third party module and try again.
