### ISSUE TITLE
Show FAQ page on custom page?

### ISSUE THREAD

**Issue by mhvejsel** [mageprince/magento2-FAQ#18]
Hello, can i not show the FAQ on a custom content page?
I want to add some text and maybe use a sidebar ;)

Thanks.

**Comment by mageprince** [comment]
Hi @mhvejsel 
Use faq CSS and js in <head>.
```
<head>
    <css src="Prince_Faq/css/faq.css"/>
    <link src="Prince_Faq/js/faq.js"/> 
</head>
```
And call FAQ phtml in <referenceContainer name="content"> or where you want to show FAQ in custom page layout xml

`<block class="Prince\Faq\Block\Index\Index" name="index.index" template="Prince_Faq::index/index.phtml"/>`

**Comment by mikehenze** [comment]
This does not seem to work.
Can you please explain how to show the faq inside a normal cms page?

**Comment by mageprince** [comment]
@mikehenze You can now show all FAQ or show FAQ by group id on CMS or Static Block. Please download latest version of the module.
