### ISSUE TITLE
Extension did not pass the Marketplace EQP installation test

### ISSUE THREAD

**Issue by hariom-kesharwani** [mageprince/magento2-FAQ#2]
Hi Prince,
I was try to upload my plugin a market place but it didn't get approved.
What will you done to resolve the below issues (Please help me out) :
**This extension did not pass the Marketplace EQP installation test. Extensions are required to install successfully when compiled and run in production mode. You can find instructions on commandline configuration, setting the Magento mode to "Production", and compiling your code in the developer guide available at: http://devdocs.magento.com/guides/v2.1/config-guide/cli/config-cli.html Once the code supports compilation and execution in production mode, please reupload your package.**

**Comment by mageprince** [comment]
Hi **@hariom-kesharwani**
You should post an issue only regarding for FAQ module. Please post this type of question on https://magento.stackexchange.com

**Regarding Your Issue:**
1. Install your module in fresh Magento 2 setup with production mode.
2. You can change mode by this command:
`php bin/magento deploy:mode:set production`
3. Now run compilation
`php bin/magento setup:di:compile`

Compilation must be run successfully **without any error to pass a module to the marketplace.**
 Also, this question may help you. https://magento.stackexchange.com/questions/187509/how-to-create-a-marketplace-ready-magento-2-extension

**If you have any other issue please post issue on  https://magento.stackexchange.com/**
