### ISSUE TITLE
Accordion arrow doesn't display properly. It shows a weird box.

### ISSUE THREAD

**Issue by jtalel** [mageprince/magento2-FAQ#20]
**Preconditions:**
Magento 2.2.8
mageprince/magento2-faq --> Latest commit 070cf02  on 26 Aug 2018
LAMP server

The accordion arrow doesn't work in no web browser (chrome/firefox/ie).  Check screencapture: http://prnt.sc/odbl1v

What I did is:

- opened following file: app/code/Prince/Faq/view/frontend/web/css/faq.css 
- You'll find following lines between lines 171-180:
```
.ui-accordion .ui-state-default:after {
  content: '\e608';
  font-family: 'luma-icons';
  float: right;
}

.ui-accordion .ui-accordion-header-active:after {
  content: '\e622';
  font-family: 'luma-icons';
}
```

- I erased line specifying "content", so it is as follows:

```
.ui-accordion .ui-state-default:after {
  font-family: 'luma-icons';
  float: right;
}

.ui-accordion .ui-accordion-header-active:after {
  font-family: 'luma-icons';
}
```

I don't know how to call the arrow that should appear there so I prefer it to display nothing instead of the weird box. Result capture: http://prnt.sc/odbljk

**Comment by 4j4yk** [comment]
@jtalel its possible that in your installation, the font path is not being recognized properly.

**Comment by mageprince** [comment]
Hi @4j4yk @jtalel The issue has been resolved now. Please download latest code from the repository.
Related commit: [06abfdd52ee](https://github.com/mageprince/magento2-FAQ/commit/06abfdd52ee8efe27190f5048d4f2dddcb2425fc)
