### ISSUE TITLE
Change page url

### ISSUE THREAD

**Issue by mikehenze** [mageprince/magento2-FAQ#21]
Hi, how can we change the urlkey from faq to something else (for each storeview)?

**Comment by mageprince** [comment]
Hi @mikehenze 
The current version of this module does not provide this functionality. I will implement this functionality in the next version of the module.

**Comment by mageprince** [comment]
hi @mikehenze 
We have implemented dynamic FAQ URL functionality in the latest version of this module. You can change FAQ url from **Admin->FAQ->Settings->FAQ Url** 

Please download from [Magento Marketplace](https://marketplace.magento.com/prince-module-faq.html) or [GitHub](https://github.com/mageprince/magento2-FAQ).
