### ISSUE TITLE
Schema.org FAQ

### ISSUE THREAD

**Issue by mikehenze** [mageprince/magento2-FAQ#22]
Hi, please consider support the schema.org faq schema

**Comment by mageprince** [comment]
Hi @mikehenze 
Recently I have added meta fields in FAQ configurations. Please check commit: [80947e](https://github.com/mageprince/magento2-FAQ/commit/80947e6d86eb1d675515b3ca99cfe3c872597c75) or
Download latest repository code.

**Comment by mikehenze** [comment]
This is for meta data.
I am talking about faq rich snippets, see:
https://searchengineland.com/google-confirms-new-faqs-qa-and-how-tos-for-search-results-snippets-303116
