### ISSUE TITLE
Magento 2.3.0 Category icon

### ISSUE THREAD

**Issue by scormbuilder** [mageprince/magento2-FAQ#24]
Greeting,
when I tried to upload png or jpg photo as category icon the system keeps loading and nothing happened, any ideas..?

Best Regards

**Comment by mageprince** [comment]
@Dybala2 Can you please provide console error screenshot.

**Comment by scormbuilder** [comment]
@mageprince 
Dear Prince, I would like to thank you for this great extension ... it's working fine and I can live with the default icon only, however could you please clarify how I can get the console error?

**Comment by mageprince** [comment]
@Dybala2 Right-click on browser-> Inspect -> Go to console tab and take a screenshot.

**Comment by scormbuilder** [comment]
@mageprince [https://prnt.sc/pqvz4y](url)
 console tab PrintScreen

**Comment by mageprince** [comment]
@Dybala2 Screenshot link is broken

**Comment by scormbuilder** [comment]
@mageprince please copy the link and paste it in the browser

**Comment by mageprince** [comment]
@Dybala2 Please change **"fileUploader"** to **"imageUploader"** at line number 87 in file
https://github.com/mageprince/magento2-FAQ/blob/a1b7977663ad10b31eb6cfea7b3b4c5f89ba92d4/view/adminhtml/ui_component/prince_faqgroup_form.xml#L87
