### ISSUE TITLE
FAQ Groups Aligning 

### ISSUE THREAD

**Issue by asriva** [mageprince/magento2-FAQ#27]
The FAQ icon groups do not stay centred with different device sizes. 
For example-: If I have created 4 FAQ Groups, on the frontend they are always left-aligned. It would be great if these groups can be aligned to the centre and be responsive according to the devices. See the screenshot below for more information. 
Thank you. 
Aman
![FAQ](https://user-images.githubusercontent.com/57280226/72227017-e42d9280-35eb-11ea-9f8f-8260751acbc0.png)
![FAQ1](https://user-images.githubusercontent.com/57280226/72227035-0aebc900-35ec-11ea-8169-decb78b7633a.png)

**Comment by mageprince** [comment]
Hi @asriva, Issue resolved now. Please download the latest repository or check commit: [bf70115](https://github.com/mageprince/magento2-FAQ/commit/bf70115e05a88161d4af82d9fb8c1a62b18486e6)

**Comment by asriva** [comment]
Thanks @mageprince it works perfectly now.
