### ISSUE TITLE
Errors after update to the last version

### ISSUE THREAD

**Issue by rafalinco** [mageprince/magento2-FAQ#28]
Hey guys, we updated today mageprince /Faq on magento 2 to the last version 1.0.6; 

Hey guys, our siteweb on magento 2 was working fine since  today that we updated Mageprince/Faq module to the last version; 
Module updated to 1.0.6 on magento 2, but after that we got an error when try to enter in backend to FAQ > 

Manage FAQGroup- SHOW ERROR
Manage FAQ-  SHOW ERROR
Settings- WORKING
****************************************************
Error:1 exception(s):
Exception #0 (InvalidArgumentException): Class argument is invalid: Magento\Framework\View\Element\UiComponent\Context

Exception #0 (InvalidArgumentException): Class argument is invalid: Magento\Framework\View\Element\UiComponent\Context
<pre>#1 Magento\Framework\Data\Argument\InterpreterInterface\Proxy->evaluate() called at [vendor/magento/framework/Data/Argument/Interpreter/Composite.php:61]
#2 Magento\Framework\Data\Argument\Interpreter\Composite->evaluate() called at [vendor/magento/module-ui/Config/Data.php:164]
#3 Magento\Ui\Config\Data->evaluateComponentArguments() called at [vendor/magento/module-ui/Config/Data.php:111]
#4 Magento\Ui\Config\Data->initData() called at [vendor/magento/module-ui/Config/Data.php:136]
#5 Magento\Ui\Config\Data->get() called at [vendor/magento/framework/View/Layout/Reader/UiComponent.php:100]
#6 Magento\Framework\View\Layout\Reader\UiComponent->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#7 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Layout/Reader/Container.php:89]
#8 Magento\Framework\View\Layout\Reader\Container->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#9 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Page/Config/Reader/Body.php:68]
#10 Magento\Framework\View\Page\Config\Reader\Body->interpret() called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#11 Magento\Framework\View\Layout\ReaderPool->interpret() called at [vendor/magento/framework/View/Layout.php:325]
#12 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:89]
#13 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#14 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#15 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#16 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Page/Config.php:224]
#17 Magento\Framework\View\Page\Config->build() called at [vendor/magento/framework/View/Page/Config.php:247]
#18 Magento\Framework\View\Page\Config->getTitle() called at [generated/code/Magento/Framework/View/Page/Config/Interceptor.php:50]
#19 Magento\Framework\View\Page\Config\Interceptor->getTitle() called at [app/code/Prince/Faq/Controller/Adminhtml/FaqGroup/Index.php:61]
#20 Prince\Faq\Controller\Adminhtml\FaqGroup\Index->execute() called at [generated/code/Prince/Faq/Controller/Adminhtml/FaqGroup/Index/Interceptor.php:24]
#21 Prince\Faq\Controller\Adminhtml\FaqGroup\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#22 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#23 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#24 Prince\Faq\Controller\Adminhtml\FaqGroup\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#25 Prince\Faq\Controller\Adminhtml\FaqGroup\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/WeltPixel/Backend/Plugin/Utility.php:76]
#26 WeltPixel\Backend\Plugin\Utility->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#27 Prince\Faq\Controller\Adminhtml\FaqGroup\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#28 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#29 Prince\Faq\Controller\Adminhtml\FaqGroup\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#30 Prince\Faq\Controller\Adminhtml\FaqGroup\Index\Interceptor->___callPlugins() called at [generated/code/Prince/Faq/Controller/Adminhtml/FaqGroup/Index/Interceptor.php:39]
#31 Prince\Faq\Controller\Adminhtml\FaqGroup\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#32 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:98]
#33 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#34 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#35 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#36 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#37 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:137]
#38 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#39 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#40 Magento\Framework\App\Bootstrap->run() called at [index.php:42]
</pre>

Can you help us to fix that?
Thanks
Best Regards

**Comment by mageprince** [comment]
@rafalinco Thank you for raising the issue. We have updated the code. Please download latest code or check commit: [a2ddc0904](https://github.com/mageprince/magento2-FAQ/commit/a2ddc0904c81ab4050973fe6b1e4bbaa074668f3) [8c31cfc9e](https://github.com/mageprince/magento2-FAQ/commit/8c31cfc9e45c6e4eb23ab27664c2578c7d2308c5)
