### ISSUE TITLE
FAQ Url Rewrite

### ISSUE THREAD

**Issue by trucatchtraps** [mageprince/magento2-FAQ#30]
Latest version 1.0.7. Every time you Save Config for the FAQ settings, it creates a URL Rewrite which points to the URL you had set before so it gets stuck in a loop. Deleting the URL Rewrite fixes the issue, but you should not have to do that.

**Comment by mageprince** [comment]
@trucatchtraps Thank you for posting an issue.
There is only one URL rewrite generated. If admin re-save FAQ configuration it's finds for the same URL to replace with a new custom FAQ URL.

The reason for adding URL rewrite is, Magento Marketplace raised the issue like the main faq URL should not work after adding custom URL. So we add these URL rewrites to redirect the main URL to custom URL.

**Comment by trucatchtraps** [comment]
Correct, but you have to remove the URL Rewrite otherwise the page will try to load in an infinite loop. Remove the URL Rewrite and the page loads just fine. As soon as you save the Config again, it creates the URL Rewrite again, which I then have to delete to view the FAQ page.

**Comment by mageprince** [comment]
@trucatchtraps The issue has been resolved now. Please check the commit: [8c9bde2e](https://github.com/mageprince/magento2-FAQ/commit/8c9bde2e70d83b68820fc2a9936a8968f75da028) or download latest repository.
