### ISSUE TITLE
Move Main menu inside Content Tab

### ISSUE THREAD

**Issue by paugnu** [mageprince/magento2-FAQ#33]
There are many extensions which create a new main menu entry and this ends up being kind of a mess. I think that the FAQ module should be under the content TAB.

Please check the Magento best practices:
https://devdocs.magento.com/guides/v2.3/ext-best-practices/admin/placement-and-design.html

Thanks if you take this into consideration :)

**Comment by mageprince** [comment]
@catgento Thank you for your suggestion. We will add this in the future version of the FAQ extension.
