### ISSUE TITLE
Accordian not showing

### ISSUE THREAD

**Issue by mohanwbsofttech** [mageprince/magento2-FAQ#34]
I am using your module but the accordion are not showing.

**Comment by mageprince** [comment]
@mohanwbsofttech Can you please describe the issue with more description and screenshots.

**Comment by mohanwbsofttech** [comment]
this is my page http://development.theacrylicstore.co.uk/faq/. The accordion for the que and ans are not showing

**Comment by mageprince** [comment]
@mohanwbsofttech It looks like jquery does not load onto the page. Please set the default Magento Luma theme and check again.

**Comment by mageprince** [comment]
Close this issue due to inactivity
