### ISSUE TITLE
Permissions issue on edit FAQ item

### ISSUE THREAD

**Issue by sadamson-meta** [mageprince/magento2-FAQ#35]
I have all of the boxes for FAQ checked for a user role, but while logged in as a user with the specified role, and try to edit an existing FAQ entry I get: Sorry, you need permissions to view this content.

When I go into User Roles and Resources I have every check marked for FAQ and FAQ Group. 

We are able to edit FAQ items as Administrator but I don't want to give out Admin accounts for things like this.

Magento 2.3

**Comment by mageprince** [comment]
@sadamson-meta We recently solved this issue. Please check the commit: [474e416b9](https://github.com/mageprince/magento2-FAQ/commit/474e416b9f40c12a907bdc4d0b2b71075b019d5a)
Or download the latest repository code.
### EDIT:
Now also marketplace module updated.
