### ISSUE TITLE
accordeon is not a function error

### ISSUE THREAD

**Issue by PiroozMB** [mageprince/magento2-FAQ#4]
Hi 
When I clear all the caches of my browser and open my homepage (http://dev:dev@magento2.amanvida.eu/nl) and from there I go to my faq page (http://dev:dev@magento2.amanvida.eu/nl/faq) then the accordeons won'l with an error: Accordeon is not a function. Notice that this only hapens when i clear the browser all caches and go to homepage and from there i go to my faq.

**Comment by mageprince** [comment]
@PiroozMB, thank you for your report.
We were not able to reproduce this issue by following the steps you provided. Please try to reproduce this issue on a clean/default installation or latest release.
