### ISSUE TITLE
FAQs everything visible when after page loaded

### ISSUE THREAD

**Issue by chequille** [mageprince/magento2-FAQ#40]
Hi Prince,
using your FAQ extension and it is working fine in general, but there is one small issue where I do not know what could cause this behaviour.
FIrst additional information for you, I am using Magento2 2.3.5-p2 and the lastest version here from github of your module

Ok, when I load the faq page everything is visible for lets say 1-2 seconds, before it is changing to the correct collabsed view.
It looks first as in the scrennshot below:
![grafik](https://user-images.githubusercontent.com/15807794/92659982-c985f780-f2f9-11ea-8463-e4c0b44e195a.png)

And after 1-2s like it should:
![grafik](https://user-images.githubusercontent.com/15807794/92660057-ef130100-f2f9-11ea-9b43-0c31272f6eb5.png)

After this everything works fine.

Do you have any idea what could cause this?

Looking forward to hearing from you.

Best regards,
Jürgen

**Comment by chequille** [comment]
Hi Prince,
in the case you did not understand what I mean I attach here a vieo where it is showing the behaviour of the aaccordion.

[Aufnahme #11.zip](https://github.com/mageprince/magento2-FAQ/files/5211381/Aufnahme.11.zip)

**Comment by mageprince** [comment]
Hi @chequille Thank you for your feedback. This issue has been resolve now. Please download the latest code from the repository.
Related commit: [06abfdd52ee](https://github.com/mageprince/magento2-FAQ/commit/06abfdd52ee8efe27190f5048d4f2dddcb2425fc)
