### ISSUE TITLE
FAQ URL Page Accessible from Every URL

### ISSUE THREAD

**Issue by mindfriction** [mageprince/magento2-FAQ#41]
Hello,

I installed this extension and noticed that the FAQ page is accessible from every URL. For example,

https://website.com/product-page-1/faq
https://website.com/product-page-2/faq
https://website.com/customer-service/faq
..
..

Even on your demo page:
https://demo.mageprince.com/faq/
https://demo.mageprince.com/women.html/faq
https://demo.mageprince.com/customer-service/faq

**Comment by mageprince** [comment]
Hi @mindfriction Thanks for your report.
This issue has been resolve now. Relates commit: [b500ba3d](https://github.com/mageprince/magento2-FAQ/commit/b500ba3da358edbb77685066f412d8030f5c3585)
