### ISSUE TITLE
Selecting two ore even more groups in block wizard

### ISSUE THREAD

**Issue by chequille** [mageprince/magento2-FAQ#42]
Hi Prince,

would be a nice feature if it would be possiblle to define more than one group id in the block call. At the moment only one id can be specified.

For example it could look like group_id="1,2,5,7" or something like this.

Maybe you can add this to your feature list.

Have a nice day
Reagrds,
Chequille

**Comment by mageprince** [comment]
Hi @chequille Thanks for the suggestion. We will add this feature in the future version of the extension.
