### ISSUE TITLE
Idea for a new functionality for the next version of this module for Magento 2

### ISSUE THREAD

**Issue by WesleyJustin** [mageprince/magento2-FAQ#45]
Hi employees of Mageprince,

We are very happy with the module Magento 2 FAQ! This issue is not really an issue like a bug or anything, but more of a change request / new idea to put in the module maybe for the next version.

Is it simple to add a feature where you can collapse all with a button on the top right? I don't know if that is something you would like to add to the next version. 

Please let me know if this is something you would like to add. Some customers of ours really like the module, but a couple of them are asking if this is possible, that's why I thought maybe you would like to at this.

**Comment by mageprince** [comment]
Hi @WesleyJusti,n Thank you for your suggestion. We have added this feature in the latest version of the module.
Related commit: https://github.com/mageprince/magento2-FAQ/commit/c8e8cae8bedb216ad8390811439b7c32ee15178f
