### ISSUE TITLE
Styling with CSS 

### ISSUE THREAD

**Issue by inmtl** [mageprince/magento2-FAQ#46]
I just installed the latest 2.07 version and have it configured in admin with a few test categories and faqs. In the frontend the faqs appear but without any css styling. It looks like the css found in app/code/Mageprince/Faq/view/frontend/web/css/source/_module.less is not loaded. I'm running in developer mode and have cleared / cleaned cache repeatedly. Any ideas?
Thanks

**Comment by mageprince** [comment]
Hi, @inmtl thank you for your report. Please run the below commands to compile less files.
`php bin/magento setup:upgrade`
`php bin/magento setup:static-content:deploy`
`php bin/magento cache:flush`

**Comment by inmtl** [comment]
Thanks for the quick reply. I should have mentioned that I had deployed static content several times but with no visible result on the frontend. However, I was able to get it working by adding a line to reference the css in faq_index_index.xml. 
<css src="Mageprince_Faq::css/myname.css"/> and renaming _module.less to myname.less

Now that it appears to be working as intended I'm wondering if it is possible to use fontawesome icons in place of images for Faq Groups.

Keep up the great work!

**Comment by mageprince** [comment]
Hi @inmtl Unfortunaltely we are unable to find this issue with the latest version of this module. Here is the live example of the module: https://demo2.mageprince.com/faq

Regarding use font awesome icons, you can allow icon file extension in `\Mageprince\Faq\Model\ImageUploader::$allowedExtensions` to upload icons from the admin.
