### ISSUE TITLE
Getting error on composer install

### ISSUE THREAD

**Issue by remyamr** [mageprince/magento2-FAQ#47]
Magento vertion is ver. 2.4.1

>composer require sparsh/magento-2-faq-extension

  [InvalidArgumentException]
  Could not find a matching version of package sparsh/magento-2-faq-extension. Check the package spelling, your version constraint and that the package is available
  in a stability which matches your minimum-stability (stable).

require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--skip-magento-root-plugin] [--use-default-magento-values] [--interactive-magento-conflicts] [--base-magento-edition BASE-MAGENTO-EDITION] [--base-magento-version BASE-MAGENTO-VERSION] [--] [<packages>]...

**Comment by mageprince** [comment]
Hi @remyamr Thank you for your report.
You use the wrong composer package to install. Please use below composer package:
`composer require mageprince/module-faq`
