### ISSUE TITLE
How easy it is to remove category from the urls of this extension?

### ISSUE THREAD

**Issue by VivekShingala** [mageprince/magento2-FAQ#48]
### Description (*)

1. Option to remove "category" from the url key

### Expected behavior (*)

To be able to configure if we want category in the url or not.

### Benefits

Better SEO URLs

### Example

**From**: https://www.abc.com/faqs/category/tshirts
**To**: https://www.abc.com/faqs/tshirts

**Comment by mageprince** [comment]
Hi, @VivekShingala Thank you for your report.
This module has a group option that is not included in the URL. Category option not available with this module. Maybe you checked different modules.
