### ISSUE TITLE
FAQ is not showing on footer

### ISSUE THREAD

**Issue by AveyBD** [mageprince/magento2-FAQ#5]
I have checked to show FAQ on footer. But its not showing :(

**Comment by mageprince** [comment]
@AveyBD , thank you for your report.
I am not able to reproduce this issue. Please try to reproduce this issue on a clean installation of Magento.

If you used the custom theme and custom theme not used `referenceBlock = footer_links` then FAQ link will not show in the footer. Check this file for more details: ``
https://github.com/mageprince/magento2-FAQ/blob/master/view/frontend/layout/default.xml

You can add FAQ link manually in footer block:
`<a href="{{store url='faq'}}">FAQ</a>`
