### ISSUE TITLE
Not available via composer

### ISSUE THREAD

**Issue by eBusinessAtlantique** [mageprince/magento2-FAQ#50]
Hello
Package is not available via composer with composer require prince/module-faq
Thanks for the help

**Comment by mageprince** [comment]
Dear @eBusinessAtlantique, Thank you for your report.

Please check the below points:

**1. Make sure that the [repo.Magento.com](http://repo.magento.com/) repository exists in your composer.json file at the root of Magento:**

```
"repositories": [
    {
        "type": "composer",
        "url": "https://repo.magento.com/"
    }
]
```

**2. Please check that you have the correct public and private keys in the auth.json file.**

Step to check keys:

   a. log in to Magento marketplace account (Use the same account where you buy this extension) https://developer.magento.com/customer/account/

   b. Go to My Profile -> My Products -> Access Keys

   c. Here you can find public and private keys. If you can't find any keys create a new one.

   d. Now check that you have the same public and private key in auth.json(You can find this file at the root folder of Magento)

   Use public key as the username and private key as password

   auth.json should look like this:

```
    {
        "http-basic": {
            "repo.magento.com": {
                "username": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                "password": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            }
        }
    }
```

Now please run the composer require command.

**Furthermore, Please follow this Magento Marketplace doc carefully to install the module:** https://devdocs.magento.com/cloud/howtos/install-components.html
