### ISSUE TITLE
take a look

### ISSUE THREAD

**Issue by gh-darvishani** [mageprince/magento2-FAQ#51]
Hello 
i write a module for faq graph ql based on your module but i think you remove your module from package.com or github
it is true ?
here is my module https://github.com/gh-darvishani/module-faq-graph-ql

**Comment by mageprince** [comment]
Hi @gh-darvishani, Yes, we removed the module from GitHub and the public packagist. This extension is available with the Magento marketplace. We appreciate your contribution. We will check and implement it in the next version of the module. Thank you again!
