### ISSUE TITLE
Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site. Compat.js

### ISSUE THREAD

**Issue by Davelaar** [mageprince/magento2-FAQ#52]
It was simply fixed by changing faq.js line 3.
But I am using Breeze Frontend (SwissUp Labs) with I really love but it seems to have some compatibility issues with this plugin. Can you make it compatible with breeze frontend?

**Comment by mageprince** [comment]
Hi @Davelaar This extension is commonly utilized across various Magento versions. It has been designed to be compatible with the default Luma theme. You have the flexibility to override the extension's JavaScript files and make the necessary adjustments.
