### ISSUE TITLE
Not compliant with FAQ structured data

### ISSUE THREAD

**Issue by eBusinessAtlantique** [mageprince/magento2-FAQ#54]
Search robots like Google ask for micro datas on FAQ pages.
See doc here : https://developers.google.com/search/docs/appearance/structured-data/faqpage
This module do not use micro datas. This means it will not increase your SEO.
Can micro datas be added to the module ?

**Comment by nalinilalla** [comment]
> Search robots like Google ask for micro datas on FAQ pages. See doc here : https://developers.google.com/search/docs/appearance/structured-data/faqpage This module do not use micro datas. This means it will not increase your SEO. Can micro datas be added to the module ?

This is not an issue, this is a feature request

**Comment by mageprince** [comment]
Hi @eBusinessAtlantique Unfortunately, this feature is not included in this extension. Since it's a free version, it comes with limited features.
