### ISSUE TITLE
Deprecated Back Button Error on Php 8.2

### ISSUE THREAD

**Issue by nalinilalla** [mageprince/magento2-FAQ#55]
See deprecated error on add/edit FAQ question

`1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Mageprince\Faq\Block\Adminhtml\Faq\Edit\BackButton::$context is deprecated in 
/public_html/vendor/mageprince/module-faq/Block/Adminhtml/Faq/Edit/GenericButton.php on line 34

<pre>#1 Mageprince\Faq\Block\Adminhtml\Faq\Edit\GenericButton->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#2 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]
#3 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#4 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/View/Element/UiComponent/Control/ButtonProviderFactory.php:39]
#5 Magento\Framework\View\Element\UiComponent\Control\ButtonProviderFactory->create() called at [vendor/magento/framework/View/Element/UiComponent/Context.php:300]
#6 Magento\Framework\View\Element\UiComponent\Context->addButtons() called at [vendor/magento/module-ui/Component/AbstractComponent.php:115]
#7 Magento\Ui\Component\AbstractComponent->prepare() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:164]
#8 Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:142]
#9 Magento\Framework\View\Layout\Generator\UiComponent->generateComponent() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:103]
#10 Magento\Framework\View\Layout\Generator\UiComponent->process() called at [vendor/magento/framework/View/Layout/GeneratorPool.php:93]
#11 Magento\Framework\View\Layout\GeneratorPool->process() called at [vendor/magento/framework/View/Layout.php:365]
#12 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:68]
#13 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#14 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:65]
#15 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#16 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:271]
#17 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:896]
#18 Magento\Framework\View\Layout->getBlock() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:293]
#19 Magento\Framework\View\Layout\Interceptor->getBlock() called at [vendor/magento/module-backend/Model/View/Result/Page.php:26]
#20 Magento\Backend\Model\View\Result\Page->setActiveMenu() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:23]
#21 Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu() called at [vendor/mageprince/module-faq/Controller/Adminhtml/Faq/Edit.php:62]
#22 Mageprince\Faq\Controller\Adminhtml\Faq\Edit->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#23 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#24 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#25 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->___callPlugins() called at [generated/code/Mageprince/Faq/Controller/Adminhtml/Faq/Edit/Interceptor.php:23]
#26 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#27 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#28 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#29 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#30 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:145]
#31 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#32 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Webkul/MpSellerGroup/Plugin/App/Action/Context.php:57]
#33 Webkul\MpSellerGroup\Plugin\App\Action\Context->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#34 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [app/code/Webkul/Marketplace/Plugin/App/Action/Context.php:56]
#35 Webkul\Marketplace\Plugin\App\Action\Context->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#36 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#37 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->___callPlugins() called at [generated/code/Mageprince/Faq/Controller/Adminhtml/Faq/Edit/Interceptor.php:32]
#38 Mageprince\Faq\Controller\Adminhtml\Faq\Edit\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#39 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#40 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:146]
#41 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#42 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#43 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#44 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#45 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#46 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#47 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#48 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>`

**Comment by mageprince** [comment]
Hi @nalinilalla Thank you for reporting the issue. Kindly furnish the steps to reproduce the problem and specify the Magento version you are currently using.

**Comment by nalinilalla** [comment]
Hi, @mageprince, it's 2.4.6 on php 8.2

faq>Manage faq>add new faq (error)
On click of the add new faq button

Existing 'this is a test faq' edit button (error)
On click of the edit button

**Comment by mageprince** [comment]
Hi @nalinilalla The issue has been successfully resolved, and a new version (2.1.3) of the extension has been released on the Magento Marketplace. Kindly proceed with upgrading the extension to the latest version in your store.

<img width="472" alt="image" src="https://github.com/mageprince/magento2-FAQ/assets/24751863/3b96aff4-1b25-4ced-b80e-fc119da87b61">
