### ISSUE TITLE
Class Mageprince\Base\Helper\Data does not exist

### ISSUE THREAD

**Issue by supriyac101** [mageprince/magento2-FAQ#56]
Getting bellow issues when run setup:di:compile

In ClassReader.php line 45:

  Impossible to process constructor argument Parameter #3 [ <required> Mageprince\Base\Helper\Data $baseHelper ] of Mageprince\Faq\Helper\Data class

In ClassReader.php line 34:

  Class Mageprince\Base\Helper\Data does not exist

setup:di:compile

**Comment by mageprince** [comment]
Hi @supriyac101 You might be using an older version of the extension. In the latest version, we've eliminated the dependency on the Base module. Please update the extension to the newest version to resolve this problem.
