### ISSUE TITLE
Not working in Magento 2.2.2 - Production Mode

### ISSUE THREAD

**Issue by Vikram0811** [mageprince/magento2-FAQ#6]
Installed the extension successfully in Mage version 2.2.2. When tried to access admin, it keeps loading forever and throws below exception. Neither FAQ nor FAQ Group is loading in admin. The store is set to production mode.

`Failed to load the "Magento_Ui/js/grid/editing/editor" component.`

When the store is set back to development mode, it works as expected.

How do I resolve it?

Thanks

**Comment by mageprince** [comment]
Hi @Vikram0811 Thank you for your report.
This module is tested with production mode in all 2.1.x and 2.2.x. Please download latest repository and check it with default magento installation.
