### ISSUE TITLE
After Install 504 Error

### ISSUE THREAD

**Issue by imnkit** [mageprince/magento2-FAQ#7]
Hi,

After installation, I got 504 error. When I disabled then website works fine. PFA screen for your reference.

![image](https://user-images.githubusercontent.com/665301/42496103-a6a642ba-8442-11e8-8fb4-42d2d59323cb.png)

**Comment by mageprince** [comment]
Hi @imnkit Thanks for your report But this module is already tested from Magento version 2.1.x to 2.2.3.
Please try to install it with default Magento setup and check error logs for additional error.
