### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by FedeltaMedia** [mageprince/magento2-FAQ#8]
How can we set or change the Blog page title?

**Comment by trucatchtraps** [comment]
I had to customize the module to do this as well. In your custom theme, create the directory Prince_Faq/layout. Copy the faq_index_index.xml file to this new directory. Use something like this, which will add the title and breadcrumbs: 

    <?xml version="1.0" ?>
    <page layout="1column" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
	
	<head>
        <title>Frequently Asked Questions</title>
        
         
    </head>
		
	
	<body>
	
		<referenceBlock name="page.main.title">
			<action method="setPageTitle">
				<argument translate="true" name="title" xsi:type="string">Frequently Asked Questions</argument>
			</action>
		</referenceBlock>
		
		<referenceBlock name="breadcrumbs">
            <action method="addCrumb">
                <argument name="crumbName" xsi:type="string">Home</argument>
                <argument name="crumbInfo" xsi:type="array">
                    <item name="title" xsi:type="string">Home</item>
                    <item name="label" xsi:type="string">Home</item>
                    <item name="link" xsi:type="string">{{baseUrl}}</item>
                </argument>
            </action>
            <action method="addCrumb">
                <argument name="crumbName" xsi:type="string">Frequently Asked Questions</argument>
                <argument name="crumbInfo" xsi:type="array">
                    <item name="title" xsi:type="string">Frequently Asked Questions</item>
                    <item name="label" xsi:type="string">Frequently Asked Questions</item>
                </argument>
            </action>
            </referenceBlock>
		
		
		
	</body>
    </page>

**Comment by mageprince** [comment]
Hi @trucatchtraps Thanks for your reply.

**Comment by mageprince** [comment]
Hi @Fidelity88 You can add the title in 

> view/frontend/layout/faq_index_index.xml

`<referenceBlock name="page.main.title">
        <action method="setPageTitle">
            <argument translate="true" name="title" xsi:type="string">FAQ Page</argument>
        </action>
    </referenceBlock>`

I will add this improvment in next version of this module.
